=== TiagoDeMatosDias/pyAccounting/Documentation/Config Files/schema/schema_parser_n26.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string",
      "minLength": 1
    },
    "DefaultCurrency": {
      "type": "string",
      "minLength": 1
    },
    "SubAccounts": {
      "type": "string",
      "minLength": 1
    },
    "UndefinedAccount": {
      "type": "string",
      "minLength": 1
    },
    "input": {
      "type": "string",
      "minLength": 1
    },
    "DateColumn": {
      "type": "string",
      "minLength": 1
    },
    "DateFormat": {
      "type": "string",
      "minLength": 1
    },
    "separator": {
      "type": "string",
      "minLength": 1
    },
    "RulesTable": {
      "type": "string",
      "minLength": 1
    },
    "RulesTable_Separator": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "Name",
    "DefaultCurrency",
    "SubAccounts",
    "UndefinedAccount",
    "input",
    "DateColumn",
    "DateFormat",
    "separator",
    "RulesTable",
    "RulesTable_Separator"
  ]
}

=== TiagoDeMatosDias/pyAccounting/Files/config/parser_wise.json
{
    "Name": "wise",
    "DefaultCurrency": "EUR",
    "SubAccounts": "Assets:Banks:Wise:Cash",
    "UndefinedAccount" : "Expenses:Wise:Unregistered",
    "input":"Files/input/Wise",
    "DateColumn": "Date",
    "DateFormat": "%d-%m-%Y",
    "separator": ",",
    "RulesTable": "Files/config/private/rules_Wise.csv",
    "RulesTable_Separator": ";"

}

=== TiagoDeMatosDias/pyAccounting/Files/config/parser_n26.json
{
    "Name": "n26",
    "DefaultCurrency": "EUR",
    "SubAccounts": "Assets:Banks:n26:MainAccount",
    "UndefinedAccount" : "Expenses:n26:Unregistered",
    "input":"Files/input/n26",
    "DateColumn": "Date",
    "DateFormat": "%Y-%m-%d",
    "separator": ",",
    "RulesTable": "Files/config/private/rules_n26.csv",
    "RulesTable_Separator": ";"

}
